CHORE: install Spotify package and resolve conflicts (see notes)
There were compiler errors after importing spotify package, one is a known error that has yet to be pushed production: https://github.com/spotify/spotify-web-api-ts-sdk/issues/103
I went into the file and removed the 'const' keywords, and it was resolved.

There was another error: Only named exports may use 'export type'.
This is resolved when Typescript version is >=5, I updated with npm i typescript@latest

Then there was an error  when using ng serve:  Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.
Error: Failed to initialize Angular compilation - The Angular Compiler requires TypeScript >=4.8.2 and <5.0.0 but 5.4.5 was found instead.

I found an article with commands that resolved this (source: https://stackoverflow.com/questions/75011834/how-to-fix-npm-err-while-resolving-angular-devkit-build-angular15-0-4-npm-er)
npm install --force
ng update @angular/core@15 @angular/cli@15 --force
npm config set legacy-peer-deps true